## Data Validation to check the train and test file

import numpy as np
from scipy import stats
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)
stats.ks_2samp(sample1, sample2)
KstestResult(statistic=0.5454545454545454, pvalue=7.37417839555191e-15)

In [4]:
import numpy as np
from scipy import stats
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)
response=stats.ks_2samp(sample1, sample2)

In [5]:
sample1

array([0.58263065, 0.23232891, 0.38656363, 0.34400061, 0.09487868,
       0.52976166, 0.16251401, 0.18365387, 0.21532574, 0.76991332,
       0.53888483, 0.15042452, 0.66081344, 0.17225488, 0.55428063,
       0.68657419, 0.09604383, 0.33483957, 0.19861749, 0.55105287,
       0.13862366, 0.56363012, 0.29496298, 0.8604208 , 0.26599457,
       0.44936151, 0.99403897, 0.0444006 , 0.57646376, 0.8552042 ,
       0.83506366, 0.81608998, 0.27772771, 0.69066468, 0.60489968,
       0.25173662, 0.22482709, 0.20395305, 0.25613084, 0.93839304,
       0.69456415, 0.57069962, 0.44823788, 0.5489075 , 0.69518642,
       0.87623872, 0.83514317, 0.5373615 , 0.44872493, 0.29985106,
       0.41322758, 0.63155364, 0.07195244, 0.26627607, 0.79682689,
       0.12369144, 0.61166367, 0.73484529, 0.96017625, 0.73716305,
       0.38176732, 0.45720929, 0.13173085, 0.6978941 , 0.00985072,
       0.49377636, 0.50929702, 0.93484825, 0.8557878 , 0.58757617,
       0.31382748, 0.42866031, 0.42573213, 0.04331555, 0.14754

In [6]:
sample2

array([ 1.57834082e+00,  9.53434019e-01, -6.10950179e-01,  1.09322476e+00,
        2.05586885e-01, -1.07797103e+00,  2.88415234e-01, -1.57921466e+00,
       -9.70223019e-02,  3.64502549e-01,  2.19221334e+00,  3.02329792e-01,
        4.65882998e-01,  1.73952887e+00, -1.13529122e+00, -7.59566148e-02,
        4.04742277e-01,  1.19134906e+00,  9.90955809e-01, -1.42576815e-01,
        1.49691809e+00,  2.01438796e+00, -1.42047972e-01,  1.68409241e+00,
       -1.27467936e+00,  2.00134570e+00,  1.79628302e-01,  1.41347297e+00,
        4.91099877e-01, -1.55326622e-01,  1.34496473e+00,  5.88977924e-01,
        1.35956298e+00, -4.53609173e-01,  6.92788619e-01, -3.47576592e-01,
        8.23681064e-02, -4.26643367e-01, -2.28721834e+00,  7.22669833e-01,
       -1.71610662e+00, -1.55306218e-01,  6.50394622e-01, -5.67674844e-01,
       -1.44312084e-03,  3.93752823e-01,  1.89626469e+00, -8.07819359e-01,
       -2.32040558e-01, -2.33106982e-01,  4.36047653e-01,  1.70344105e-01,
        1.55652135e+00,  

In [7]:
print(resonse.pvalue)

2.2652931717146334e-15


## Anomly in Dataset 

1. High Null Value

2.Missing Column 

3.outliers

4.categorical:

gender > MALE/FEMALE/Other





## DRIFT IN MACHINE LEARNING 

TARGET DRIFT

CONCEPT DRIFT

Data Validation

In [16]:
import pandas as pd

In [20]:
df=pd.read_csv("/config/workspace/artifacct/01312023__180004/data_ingestion/dataset/train.csv")

In [29]:
len((df.isnull().sum()/df.shape[0]).values)

171

In [25]:

(df.isnull().sum()/df.shape[0]).values

array([0.        , 0.        , 0.77001727, 0.05944732, 0.25267703,
       0.04459413, 0.04459413, 0.01074266, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01074266, 0.01074266, 0.01074266,
       0.01074266, 0.01074266, 0.01060449, 0.01063903, 0.01063903,
       0.07720207, 0.01074266, 0.01063903, 0.01074266, 0.00991364,
       0.01074266, 0.00991364, 0.04822107, 0.01063903, 0.01063903,
       0.01063903, 0.04462867, 0.04466321, 0.01070812, 0.01070812,
       0.01070812, 0.01070812, 0.01070812, 0.01070812, 0.01070812,
       0.01070812, 0.01070812, 0.01070812, 0.01070812, 0.01070812,
       0.01070812, 0.01070812, 0.01070812, 0.01070812, 0.01070812,
       0.01070812, 0.01070812, 0.01070812, 0.01098446, 0.01098446,
       0.01098446, 0.01098446, 0.01098446, 0.01098446, 0.01098446,
       0.01098446, 0.01098446, 0.01098446, 0.01060449, 0.04825561,
       0.04829016, 0.04466321, 0.04459413, 0.01074266, 0.01074266,
       0.00991364, 0.00991364, 0.38314335, 0.45336788, 0.65854

In [30]:
len((df.isnull().sum()/df.shape[0]).values)

171

In [32]:
drop_column_name=[]
for column_name,missing_percentage in zip((df.isnull().sum()/df.shape[0]).index, (df.isnull().sum()/df.shape[0]).values):
    print(column_name,missing_percentage*100)
    if missing_percentage >0.30:
        drop_column_name.append(column_name)

class 0.0
aa_000 0.0
ab_000 77.00172711571676
ac_000 5.944732297063903
ad_000 25.26770293609672
ae_000 4.459412780656304
af_000 4.459412780656304
ag_000 1.07426597582038
ag_001 1.07426597582038
ag_002 1.07426597582038
ag_003 1.07426597582038
ag_004 1.07426597582038
ag_005 1.07426597582038
ag_006 1.07426597582038
ag_007 1.07426597582038
ag_008 1.07426597582038
ag_009 1.07426597582038
ah_000 1.060449050086356
ai_000 1.063903281519862
aj_000 1.063903281519862
ak_000 7.72020725388601
al_000 1.07426597582038
am_0 1.063903281519862
an_000 1.07426597582038
ao_000 0.9913644214162348
ap_000 1.07426597582038
aq_000 0.9913644214162348
ar_000 4.822107081174439
as_000 1.063903281519862
at_000 1.063903281519862
au_000 1.063903281519862
av_000 4.46286701208981
ax_000 4.466321243523316
ay_000 1.070811744386874
ay_001 1.070811744386874
ay_002 1.070811744386874
ay_003 1.070811744386874
ay_004 1.070811744386874
ay_005 1.070811744386874
ay_006 1.070811744386874
ay_007 1.070811744386874
ay_008 1.0708117443

In [33]:
drop_column_name

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']